name: Build and Deploy Production

on:
   push:
      branches:
         - master

jobs:
   build_and_push:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - name: Build the Docker image
           run: |
              docker login -u kizoukun -p ${{ secrets.GH_TOKEN }} ghcr.io
              docker build . --tag ghcr.io/kizoukun/pufafrontend:latest
              docker push ghcr.io/kizoukun/pufafrontend:latest

   deployments:
      runs-on: ubuntu-latest
      needs: build_and_push
      environment: production
      steps:
         - name: Deploy to Production
           uses: appleboy/ssh-action@master
           with:
              host: ${{ secrets.SERVER }}
              username: ${{ secrets.SERVER_USERNAME }}
              password: ${{ secrets.SERVER_PASSWORD }}
              port: ${{ secrets.SERVER_PORT }}
              script: |
                 whoami
                 docker stop ${{ vars.CONTAINER_NAME }} || true && docker rm ${{ vars.CONTAINER_NAME }} || true
                 docker pull ${{ vars.IMAGE_NAME}}:beta
                 docker run -d -p ${{ secrets.API_PORT }}:3000 --name ${{ vars.CONTAINER_NAME }} ${{ vars.IMAGE_NAME}}
